### ISSUE TITLE
Not able to create migrations (Models aren't loaded yet.)

### ISSUE THREAD

**Issue by simonsapiel** [agconti/cookiecutter-django-rest#1154]
#### What's going wrong?

I'm not able to run `python manage.py makemigrations` locally. The error seems to be 

```
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.
```
If I understood correctly upon running `docker-compose up` the app will only migrate, but doesn't actually create the migrations so `makemigrations` should be able to run outside docker?

#### Is this a problem with a fresh install of the project?

- [x] Yes
- [ ] No

**Comment by agconti** [comment]
@simonsapiel If you're using docker-compose up, you need to also run your `makemigrations` with docker:

```
docker-compose run --rm web manage.py makemigrations
```

I'll close this issue since it's a question of how to use docker/docker-compose rather than a problem with the cookie-cutter.
