### ISSUE TITLE
Refactor settings to use Django class based settings instead of Django Configurations

### ISSUE THREAD

**Issue by agconti** [agconti/cookiecutter-django-rest#118]
https://github.com/matthewwithanm/django-classbasedsettings

**Comment by agconti** [comment]
Because django class base settings is still incompatible with django 1.9, https://github.com/matthewwithanm/django-classbasedsettings/issues/17, and because django configurations is now part of [JazzBand](https://jazzband.co/) we'll keep with the current implementation and will upgrade django configurations version

**Comment by RevolutionTech** [comment]
FYI django-classbasedsettings is now compatible with Django 1.9.
https://github.com/matthewwithanm/django-classbasedsettings/issues/17
