### ISSUE TITLE
Implement `django-push-notifications` over django-pnm

### ISSUE THREAD

**Issue by agconti** [agconti/cookiecutter-django-rest#122]
Because of ZeroPush's recent [acquisition ](https://zeropush.com/acquisition),  `django-pnm` may no longer work after January 31st. If the service shuts down, we should switch to [`django-push-notifications`](https://github.com/jleclanche/django-push-notifications) instead. 

fyi: @glemmaPaul, @vpatel85

**Comment by agconti** [comment]
@glemmaPaul @vpatel85 the service will shut down :sob: #128

**Comment by glemmaPaul** [comment]
Yeah I heard that too @agconti , this shows that all those services are just one piece of extra abstraction that only could fail.. :cry:

**Comment by agconti** [comment]
In an effort to keep this project lean and minimally opinionated, I've decided against baking push notifications in. The hope is that a more general boilerplate will better serve the community's needs and will minimize unrelated code in their projects.
