### ISSUE TITLE
Running docker-compose up on macbook air m1

### ISSUE THREAD

**Issue by branko993** [agconti/cookiecutter-django-rest#1639]
After running docker-compose up i get `bash: ./manage.py: /usr/bin/env: bad interpreter: Permission denied` error
<img width="862" alt="Screenshot 2022-07-30 at 18 59 42" src="https://user-images.githubusercontent.com/28029764/181933990-41b048cb-bbfb-4546-b8eb-6cf07293faca.png">

**Comment by agconti** [comment]
@branko993 closing this issue since this isn't specific to this project. You get this error when you haven't set up docker to run correctly with the m1 processors. Docker has excellent guides on how to do so. Once you're set up, this issue will disappear.
