### ISSUE TITLE
Error when running migrate command on Azure VM

### ISSUE THREAD

**Issue by chika-kasymov** [agconti/cookiecutter-django-rest#181]
Hello!

I have trouble to run command `python project_name/manage.py migrate` on Azure VM. The error says: 

> django.db.utils.OperationalError: fe_sendauth: no password supplied

Can you also provide instructions how to deploy to virtual machine not to Heroku?

Thanks for any help!

**Comment by agconti** [comment]
Hi @chika-kasymov, thanks for opening up an issue. 

This isn't a bug with the cookiecutter but rather an issue with the way you're calling the `migrate` command on your Azure server. While I'd love to help with instructions and further debugging, I haven't used Azure before and have no expertise with the platform. I recommend you reach out to them for further assistance. 

Good luck and thanks for contributing!
