### ISSUE TITLE
Where does settings.py go?

### ISSUE THREAD

**Issue by Bijig0** [agconti/cookiecutter-django-rest#1959]
#### How can the `cookiecutter-django-rest` team reproduce the problem?

I cannot seem to find the settings.py in the project. Where should it be added?

#### Is this a problem with a fresh install of the project?

- [ **]** Yes
- [ ] No

**Comment by tran-hai-long** [comment]
In professional environments, developers usually make multiple setting files for different purposes.
config/local.py is the settings for internal testing.
config/production.py is the settings for product deployment.
In manage.py you can see DJANGO_CONFIGURATION is set to "Local". Note that both Local and Production extend from Common, that means they both contain settings in common.py.
