### ISSUE TITLE
Is the project still actively maintained? Django 4.2

### ISSUE THREAD

**Issue by ayyssh** [agconti/cookiecutter-django-rest#2063]
Hi, 

I want to setup a DRF API backend for an enterprise ERP application. I'd like to know if this project is still actively updated and maintained?

**Comment by janlis-ff** [comment]
I don't think it is.

**Comment by stacygaudreau** [comment]
You can use the ordinary cookie cutter Django template, which is well maintained. It has an option to add Django REST Framework during its setup.

**Comment by agconti** [comment]
@hiayushh This is a cookiecutter, which means it just helps you scaffold your project. It's not a dependency of your project, so there should be no concern about maintenance. If its scaffolding is attractive to you when you're ready to start your project, feel free to use it.
