### ISSUE TITLE
django-configuration conflicts with pycharm python console

### ISSUE THREAD

**Issue by daimon99** [agconti/cookiecutter-django-rest#234]
In pycharm, when run python console:

```
ImproperlyConfigured: django-configurations settings importer wasn't correctly installed. Please use one of the starter functions to install it as mentioned in the docs: http://django-configurations.readthedocs.org/
```

May be we should remove this package .
I think django-environ is better, lighter then django-configuration

**Comment by agconti** [comment]
Hi @daimon99, 

Thanks for opening up this ticket. Does this issue occur when you run `fab serve` or only with pycharm?

**Comment by daimon99** [comment]
With pycharm. When run python-console with pycharm. It is a known issue in django-configuration.
Ref to: ["improperly installed" error when run from PyCharm, yet works on command line](https://github.com/jazzband/django-configurations/issues/147)

**Comment by agconti** [comment]
Thanks for reporting @daimon99. 

Since this is an issue with django-configuration, I'm going to close this ticket. I'm planing to remove that package in #324.
