### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by vinamelody** [agconti/cookiecutter-django-rest#337]
Hi, when I run `./manage.py migrate`, I got this error

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    from configurations.management import execute_from_command_line
ImportError: No module named 'configurations'
```

**Comment by agconti** [comment]
@vinamelody have you activated your virtualenv and installed the requirements? 

The ReadMe has a quick [walkthrough](https://github.com/agconti/cookiecutter-django-rest/blob/master/%7B%7Bcookiecutter.github_repository_name%7D%7D/README.md#initialize-the-project) of how to get started.

**Comment by agconti** [comment]
@vinamelody I'm going to close this because of lack activity. If you're still having problems feel free to open it back up 😄 .
