### ISSUE TITLE
Remove django-secure

### ISSUE THREAD

**Issue by spoetnik** [agconti/cookiecutter-django-rest#356]
As stated on http://django-secure.readthedocs.io/en/latest/

> This project was merged into Django 1.8. It does not provide any additional checks beyond those included in Django 1.8+, so there is no reason to use it with Django 1.8+. Since Django 1.8 is now the lowest supported Django version, this project is now unsupported and un-maintained.

**Comment by agconti** [comment]
Hi @spoetnik,

Thanks for opening an issue. This makes sense -- I'll remove `django-secure`. Adding this to the current release schedule.
