### ISSUE TITLE
Remove client state

### ISSUE THREAD

**Issue by spoetnik** [agconti/cookiecutter-django-rest#366]
Reading '[Lightweight Django](http://shop.oreilly.com/product/0636920032502.do)' chapter 4 'Building a REST API'
It suggest removing '`django.contrib.sessions.middleware.SessionMiddleware`' as ' the server will not maintain any client state'
Sounds reasonable don't you think?
As '`django.contrib.sessions.middleware.SessionMiddleware`' is removed, also middleware and apps dependant on this needs to be removed:
```
django.contrib.auth.middleware.AuthenticationMiddleware,
django.contrib.auth.middleware.SessionAuthenticationMiddleware, and
django.contrib.messages.middleware.MessageMiddleware
```
And `django.contrib.admin, django.contrib.sessions, django.contrib.messages` apps

**Comment by imaurer** [comment]
Just stumbled on this cookie cutter project. It looks great.

Would there be separate settings for admin functionality? Not sure how this would be best structured for clarity. 

My highlight from the same book...

"If that’s the case, you can preserve the admin and simply have two sets of settings for the project: one for the API and one for the admin. The admin settings would restore the session and messages apps along with the authentication middleware. You would also need another set of root URLs that include the admin URLs. With these configurations, some servers would serve the admin part of the site and others would serve the API. Given that in a larger application these will likely have very different scaling needs and concerns, this serves as a clean approach to achieving Django admin access."

**Comment by spoetnik** [comment]
I can add the admin (and thus session, etc) to local settings? My doubt is that local and production vary to much, so "it works on my computer" doesn't mean anything....
Maybe make a 'backoffice' settings or something, and add the admin to that?

**Comment by imaurer** [comment]
I like the idea of a separate settings that extends the existing settings and adds admin and session-based middleware, etc. to it. The name "backoffice" is pretty good, was going to suggest "admin" but that would probably end up being a conflict. Maybe "administration"?

**Comment by spoetnik** [comment]
@agconti Do you have a preferred opinion?

**Comment by spoetnik** [comment]
I have added a "Backoffice' setting.

**Comment by EralpB** [comment]
Removing state would be amazing, true RESTful power! :) but I think it would complicate the admin panel for new users. maybe include this as a switch in settings.py?

**Comment by agconti** [comment]
@spoetnik thanks for your enthusiasm and contribution!

I'm going to close this issue based on this project's [core values](https://github.com/agconti/cookiecutter-django-rest/issues/364#issuecomment-354171879):

> The idea behind this project is to have the slimmest possible boilerplate while maximizing developer productivity from the get-go. [This] isn't something that I think the project should support out of the box because it's a specific use case. While many will find it useful, many others won't have a need for it.
>
> If this is something that you'd like to maintain yourself -- I encourage you to fork the project!

Removing session storage as you've outlined adds additional complexity to settings configuration. While some users, like yourself, will want to remove session storage so that there's no chance they violate RESTful guidelines. Most users will be content to just not use session storage or would like the option to violate RESTful guidelines with session storage when they think its best for their project. 

You seem very passionate about this so please fork the project and customize it your own liking!
