### ISSUE TITLE
Nose not picking up tests

### ISSUE THREAD

**Issue by sohaibfarooqi** [agconti/cookiecutter-django-rest#416]
Hi,
I have successfully set up cookiecutter and have another subdirectory call `teams` to it. I have put it in installed apps but when i run `python <proj>/manage.py test <proj>` nose don't discover test under teams subdirectory. Users and authentication tests runs fine. Can you tell me what configuration i need to do so that nose discovers my tests?

Thanks

**Comment by sohaibfarooqi** [comment]
I have `__init__.py` in all subdirs. I have also tried 

 - `chmod 644 test_view.py`
 - `--exe` flag to test runner
 - `export NOSE_INCLUDE_EXE=1`

**Comment by LeCoupa** [comment]
I can run test for specific apps e.g.

`python project/manage.py test app_name`

but when I run

```
python project/manage.py test
0 tests was found
```

Figure out I need to run this in the same directory as manage.py

so the solution would be, cd to project directory and run

`python manage.py test`

**Comment by agconti** [comment]
Hey @sohaibfarooqi, @LeCoupa is correct you need to run the test command from project directory.
