### ISSUE TITLE
fab init: 

### ISSUE THREAD

**Issue by mpachas** [agconti/cookiecutter-django-rest#425]
Hi! I've just get everything working, but I had to comment the line which promotes the database because heroku returns a error/warning code if it was already the main db (It is the only one, so it will be always the main one).

I also had to create an static folder at root level with an empty file in order to get collectstatic working too.

**Comment by agconti** [comment]
Hey @mpachas, thanks for bringing these bugs up! ✨

Both were patched in #324. 😄  🎉
