### ISSUE TITLE
Deploy on Heroku: No module named 'configurations'

### ISSUE THREAD

**Issue by FireZenk** [agconti/cookiecutter-django-rest#485]
So I'm trying to deploy on Heroku from Github (but also from Travis) my project created with this tool, but I'm getting this error again and again: 
```bash
2017-11-06T11:04:39.643642+00:00 app[web.1]:     return util.import_app(self.app_uri)
2017-11-06T11:04:39.643643+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
2017-11-06T11:04:39.643644+00:00 app[web.1]:     __import__(module)
2017-11-06T11:04:39.643644+00:00 app[web.1]:   File "/app/myapp/wsgi.py", line 14, in <module>
2017-11-06T11:04:39.643645+00:00 app[web.1]:     from configurations.wsgi import get_wsgi_application    # noqa
2017-11-06T11:04:39.643651+00:00 app[web.1]: ModuleNotFoundError: No module named 'configurations'
```

My wgsi:

```python
"""
WSGI config for myapp project.

It exposes the WSGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/howto/deployment/wsgi/
"""
import os

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config")
os.environ.setdefault("DJANGO_CONFIGURATION", "Production")

from configurations.wsgi import get_wsgi_application    # noqa
from whitenoise.django import DjangoWhiteNoise          # noqa

application = DjangoWhiteNoise(get_wsgi_application())

```

Any ideas?

**Comment by agconti** [comment]
@FireZenk That error often occurs when you haven't pip installed or activated the virtualenv. Can you confirm that you have?

**Comment by FireZenk** [comment]
Is it necessary to have a virtualenv on Heroku? I've pip and all the preferences installed

**Comment by agconti** [comment]
Hey @FireZenk its not necessary to have a virualenv on Heroku.

I apologize, only pip installing is relevant to you. That error just occurs so often during local development. 😅 

I ran the project locally  and deployed and everything worked fine. Did this error occur with a just the result of the scaffold or after additions?

**Comment by FireZenk** [comment]
Is just when I try to deploy the branch from Heroku ui, the error is the same over and over

```
File "/app/project/wsgi.py", line 14, in <module>
     import configurations  # noqa
ImportError: No module named configurations
```

**Comment by agconti** [comment]
@FireZenk Is this from a fresh scaffold?

Without anything more to go on then the `ImportError`, it seems like the dependency isn't installed and once you install it you'll be good to go. 

Can you test this theory by running the project locally? You can also test this deployed by pip freezing before you start the server and checking that `configurations` is in the output. Something like:

```
web: pip freeze && gunicorn --pythonpath=./{{yourproject}} --bind 0.0.0.0:$PORT  --log-file - wsgi:application
```

**Comment by agconti** [comment]
@FireZenk I'm going to close this issue since this thread has gone stale. If you're still having issues feel free to open this back up! ✨

**Comment by joanna350** [comment]
I was able to test locally until using the heroku run command, started seeing this error. Can you advise?
