### ISSUE TITLE
Refer to models in other apps

### ISSUE THREAD

**Issue by chrisvoncsefalvay** [agconti/cookiecutter-django-rest#489]
Assume I have created another app, which would logically be on the same level as ``users``, below the main app directory. This will be pretty problematic as I will not be able to refer to a model in, say, ``users``, as a relative import fails due to going above the top level directory and a direct import also fails altogether. 

Is this the best structure? The sample app, ``piedpiper-web``, doesn't really show a solution to this as it consists only of a single ``users`` app.

**Comment by agconti** [comment]
Hey @chrisvoncsefalvay, thanks for opening up an issue. ✨ 💡

I don't think I fully understand your question -- what's an example of an import syntax that you'd like to use? 

Currently in the project you can import other apps with a statement like:

```python
# in your blog views.py for example
from .users.models import User
```

**Comment by zookz** [comment]
@agconti move your apps one folder up to the root, and then ref them in the settings.py file .. or like me, make a apps folder in the root folder, and refer to them settings.py file like so .. apps.myapp .. hope it helps you.

**Comment by agconti** [comment]
Closing due to staleness.
