### ISSUE TITLE
README typos and clarifications

### ISSUE THREAD

**Issue by desenna** [agconti/cookiecutter-django-rest#524]
Hello,

I just got through my first cookiecutter experience and have a few small items to share:

1. 'sever' should be 'server' (e.g. 'Initializing the production sever:')
2. In the sample code for section 'Initializing the qa sever:', in order to get my heroku qa environment set up properly, I needed to add 3 '--app {{cookiecutter.app_name}}-prod'... not sure if I'm the only one who faced this issue or not
3. The first go-round I had in getting this thing setup, I started with a repo and app name that began with a number instead of a letter... this caused problems w.r.t. heroku naming policies and also with getting my tests to pass (I kept getting Django 'missing app label' errors or that I hadn't included it in INSTALLED_APPS). I had a heckuva time trying to figure this out before renaming, which solved the issue. Might be worth a mention to save time for other newbies like me, unless this is a well-understood convention.

**Comment by desenna** [comment]
BTW, if these are valid issues, happy to submit some PRs if you'd like... if so, please let me know if you'd like this as 3 separate or if one will do. Thanks

**Comment by agconti** [comment]
Hey @desenna, thanks for opening this issue up! 💖  

These issues were resolved via #520 ✨
