### ISSUE TITLE
Deployment on a VPS using Docker

### ISSUE THREAD

**Issue by blushi** [agconti/cookiecutter-django-rest#527]
Hi,

First, thanks for this project. I could run it locally quickly using docker compose and start building my API without worrying about anything else.
Now, it's time to deploy it and we have decided to deploy it on an Ubuntu VPS using Docker.
I am quite a newbie when it concerns deployment and I don't really know where to start.
Should I still use docker-compose for deployment and change `DJANGO_CONFIGURATION` from `Local` to `Production` in `wsgi.py` and `manage.py`?
I am missing something?

Thanks in advance !

**Comment by agconti** [comment]
Closing due to staleness.
