### ISSUE TITLE
Evaluate django-q to replace django-rq

### ISSUE THREAD

**Issue by agconti** [agconti/cookiecutter-django-rest#59]
https://github.com/Koed00/django-q

**Comment by auvipy** [comment]
why not celery?

**Comment by agconti** [comment]
Django-q is an awesome piece of software. Its robust queuing, scheduling, and distributed nature make it an better choice for mature applications under meaningful load. 

Django-rq will be preferred for this project because is more simple and easier to set up and manage. This will pay dividends for developers when their app is first starting. Once its matured, my recommendation is to consider more robust solutions like django-q.
