### ISSUE TITLE
Broken Link in README

### ISSUE THREAD

**Issue by ademidun** [agconti/cookiecutter-django-rest#590]
Hello, the following link on [this page](https://github.com/agconti/cookiecutter-django-rest/blob/master/%7B%7Bcookiecutter.github_repository_name%7D%7D/docs/index.md) is not working:

Try clicking on documentation.
{{cookiecutter.description}}. Check out the project's [documentation](http://%7B%7Bcookiecutter.github_username%7D%7D.github.io/%7B%7Bcookiecutter.github_repository_name%7D%7D/).

Broken Link: http://%7B%7Bcookiecutter.github_username%7D%7D.github.io/%7B%7Bcookiecutter.github_repository_name%7D%7D/

Thanks for the repo, btw. Keep up the awesome work.

**Comment by agconti** [comment]
Hey @ademidun thanks for opening up an issue! That link is actually correct; it gets templated by cookiecutter when you scaffold a project.

When scaffolding, cookiecutter will render your github username and repo  in the links address so it will point to your projects documentation hosted on github pages.  You can this out in the example repo [here](https://github.com/agconti/piedpiper-web).
