### ISSUE TITLE
Amazon elastic beanstalk example

### ISSUE THREAD

**Issue by Amurmurmur** [agconti/cookiecutter-django-rest#596]
#### Is this a problem with a fresh install of the project?

- [x] Yes
- [ ] No

I would be so grateful if you could share an example of Multicontainer Docker instance running on an AWS Elastic Beanstalk.

If you could just provide Dockerrun.aws.json and Dockerfile targeted specifically for this project.

Thank you so much in advance!

**Comment by Amurmurmur** [comment]
Here are the sample files that I use.
https://gist.github.com/Amurmurmur/cb2c46710182b437ea4d918e047b319e

**Comment by agconti** [comment]
Closing because this isn't an issue with the project.

**Comment by Amurmurmur** [comment]
@agconti True, and I've fixed the issue.

Thank you so much for the project!!!

**Comment by EralpB** [comment]
I would love to have a way to deploy to AWS.
