### ISSUE TITLE
CSRF verification failed with a freshly cloned project running in localhost

### ISSUE THREAD

**Issue by gonvaled** [agconti/cookiecutter-django-rest#616]
#### What's going wrong?

After creating user, I can not login. A Forbidden 403 site is displayed, with reference to a CSRF problem:

> Forbidden (403)
> CSRF verification failed. Request aborted.
> 
> You are seeing this message because this site requires a CSRF cookie when submitting forms. This cookie is required for security reasons, to ensure that your browser is not being hijacked by third parties.
> 
> If you have configured your browser to disable cookies, please re-enable them, at least for this site, or for 'same-origin' requests.
> 
> Help
> Reason given for failure:
> 
>     CSRF cookie not set.
>     
> In general, this can occur when there is a genuine Cross Site Request Forgery, or when Django's CSRF mechanism has not been used correctly. For POST forms, you need to ensure:
> 
> Your browser is accepting cookies.
> The view function passes a request to the template's render method.
> In the template, there is a {% csrf_token %} template tag inside each POST form that targets an internal URL.
> If you are not using CsrfViewMiddleware, then you must use csrf_protect on any views that use the csrf_token template tag, as well as those that accept the POST data.
> The form has a valid CSRF token. After logging in in another browser tab or hitting the back button after a login, you may need to reload the page with the form, because the token is rotated after a login.
> You're seeing the help section of this page because you have DEBUG = True in your Django settings file. Change that to False, and only the initial error message will be displayed.
> 
> You can customize this page using the CSRF_FAILURE_VIEW setting.

#### How can the `cookiecutter-django-rest` team reproduce the problem?

Start a new project from scratch, create the user as described in the readme:

```
» curl -d '{"username":"'"$RANDOM"'", "password":"test", "email":"test@test.com", "first_name":"test", "last_name":"user"}'      -H "Content-Type: application/json"      -X POST http://localhost:8000/api/v1/users/
{"id":"e885fc6e-50dc-4e27-bf08-02790d44bff6","username":"5572","first_name":"test","last_name":"user","email":"test@test.com","auth_token":"8399e97eba998a5fd4b816925fbfe425b7678d05"}
```
Then open a browser and login with the provided credentials in http://localhost:8000/api-auth/login/?next=/api/v1/:

Username: test@test.com
Password: test

Or:

Username: 5572
Password: test

#### Is this a problem with a fresh install of the project?

Yes

**Comment by gonvaled** [comment]
It seems this is a `localhost` issue. Using a domain name (even one pointing to `127.0.0.1`) seems to work.

Maybe worth mentioning in the README?

**Comment by agconti** [comment]
Closing as this issue has gone stale and isn't a bug in the project.
