### ISSUE TITLE
Upgrade user model `pk`s to `uuids`

### ISSUE THREAD

**Issue by agconti** [agconti/cookiecutter-django-rest#65]

**Comment by spoetnik** [comment]
If I may ask, what is the reason behind this?

Normally the .pk is an integer. Some libraries create relations on the user, and try to store the user-reference in an integer field. This breaks at the moment.

**Comment by agconti** [comment]
Hi @spoetnik, theres quite a few resources out there on uuids vs pks.  This article has a high level introduction: https://blog.codinghorror.com/primary-keys-ids-versus-guids/.

What's broken?

**Comment by spoetnik** [comment]
I am trying to use [django-scheduler](https://github.com/llazzaro/django-scheduler).
The CalendarRelation is broken when the user.pk is a UUID.
https://github.com/llazzaro/django-scheduler/blob/develop/schedule/models/calendars.py#L233

**Comment by agconti** [comment]
@spoetnik I recommend you open up an issue with `django-scheduler` or revert you user model to use primary keys.
