### ISSUE TITLE
Running ./manage.py test will result in "Coverage.py warning: Module walc was never imported."

### ISSUE THREAD

**Issue by glemmaPaul** [agconti/cookiecutter-django-rest#67]
This is a new bug that is caused by the coverage package. I'm not sure how we could resolve this issue or if we ever want to do that. It's a personal preference to be in the app folder instead of the repo folder.

Any thoughts @agconti?

**Comment by agconti** [comment]
@glemmaPaul I just did a fresh pull of the repo and did a fresh pip install and didn't run into any issues: 

![coverage-no-error](https://cloud.githubusercontent.com/assets/3332051/9455367/9891aa2a-4a98-11e5-9f3a-168c8e285f89.gif)

What version of coverage are you using? Also can you share the full stack trace?

**Comment by glemmaPaul** [comment]
@agconti Try to go into the `piedpiper` folder and type in `python manage.py test` in that folder, that should break the coverage.

**Comment by agconti** [comment]
@glemmaPaul is `walc` the name of your app?

**Comment by agconti** [comment]
May be related to #73

**Comment by agconti** [comment]
@glemmaPaul I need some more time to check this out. I'll get back to you.

**Comment by agconti** [comment]
@glemmaPaul let me know if you make any progress on it in the meantime :smiley:

**Comment by agconti** [comment]
@glemmaPaul just posted a fix in #67. Please give it a try and let me know if it works for you  :smiley:. Also, I'm running into #75, so I'll have to fix that separately.

**Comment by glemmaPaul** [comment]
@agconti I'm sorry I didn't respond to all these messages! Didn't get any notification, will keep an eye for new comments from now on :)!

**Comment by agconti** [comment]
@glemmaPaul no worries.
