### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

### ISSUE THREAD

**Issue by tluanga** [agconti/cookiecutter-django-rest#708]
while running python manage.py runserver , i am getting this error kindly help
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

**Comment by simon-moon** [comment]
It appears that the SECRET_KEY is set by a call to os.getenv('DJANGO_SECRET_KEY')

You will need to set DJANGO_SECRET_KEY in your development environment.

or change

SECRET_KEY = os.getenv('DJANGO_SECRET_KEY') 

to

SECRET_KEY = 'WHATEVERKEYHERE'

**Comment by agconti** [comment]
@tluanga this is also configured for you in your [`docker-compose.yml`](https://github.com/agconti/cookiecutter-django-rest/blob/master/%7B%7Bcookiecutter.github_repository_name%7D%7D/docker-compose.yml#L9). To run the project with docker compose use: 

```bash
docker-compose up
```

Also check out the [docs](https://github.com/agconti/cookiecutter-django-rest/blob/master/%7B%7Bcookiecutter.github_repository_name%7D%7D/README.md#local-development) included in your project for instructions on how to develop locally.
