### ISSUE TITLE
Heroku requires a new "release phase" for deploying pushed Docker images

### ISSUE THREAD

**Issue by chrisjcook** [agconti/cookiecutter-django-rest#719]
#### What's going wrong?
Followed setup as best as I could, but Heroku fails to actually deploy, or log any activity at all in the Heroku dashboard.
![travisci-docker-heroku](https://user-images.githubusercontent.com/5895392/44050589-37981942-9eec-11e8-9fcc-ffff6a82d3da.png)

#### How can the `cookiecutter-django-rest` team reproduce the problem?
Complete a fresh install of the project, right up until the point of pushing to master/qa and having TravisCI build and attempt to deploy your docker image.

After doing a bit of poking around, I figured this could be the reason for it not working:
https://devcenter.heroku.com/changelog-items/1426

With that being said, I actually see *no* activity in my Heroku dashboard after actually creating each project (prod/qa). So something else might be off. Let me know if there's any other information that could be helpful here!

#### Is this a problem with a fresh install of the project?

- [x] Yes
- [ ] No

**Comment by chrisjcook** [comment]
**Update**
I got it to deploy by sort of following some deployment steps in the Heroku dashboard:

**Log in to Container Registry**
```
$ heroku login
```
You must have Docker set up locally to continue. You should see output when you run this command.
```
$ docker ps
```
Now you can sign into Container Registry.
```
$ heroku container:login
```
**Deploy the changes**
Release the newly pushed images to deploy your app.
```
$ heroku container:release --app <APP_NAME> web
```

I'm still having some issues with my deployment -- namely I didn't set up the AWS keys/etc. because I didn't think they were required, but it seems like when deploying/releasing the app this breaks everything because the bucket doesn't exist (?)

In any case, this step was confusing and could probably be improved / better documented.

**Comment by agconti** [comment]
Hey @chrisjcook, 

Thanks for opening up this issue and tracking the problem down. I'll take a look at updating the deployment steps in `.travis.yml`.

**Comment by manticarodrigo** [comment]
Hey @chrisjcook and @agconti. I'm having deployment issues as well. It would be nice to have the entire process (with and without travis) documented.

Sidenote: I'm using django-storages with google storage so I had to comment out the AWS settings.

**Comment by agconti** [comment]
@manticarodrigo feel free to open a PR with some more documentation! 😅✨

This project isn't intended to be an exhaustive resource of the multitude of ways that you can deploy your app and setup CI/CD for it. Those providers will always have more up-to-date and comprehensive documentation than this project could hope to duplicate. In this case, I'd encourage you to check out Heroku's [deployment docs](https://devcenter.heroku.com/articles/container-registry-and-runtime) for help around the issues you're encountering. 

The project aims to give you the foundation and flexibility to deploy anywhere.  For convenience, its configured out of the box for a simple deployment to heroku via travis thats suitable for small apps and internal development, like staging / QA servers. Many users will choose different deployment providers and strategies that suite them better. Some may keep some of the scaffolding. Some may not. Thats intended. Support on that path, like configuring google storage over s3, is up to user and is out of scope and the goals of this project.
