### ISSUE TITLE
RelatedObjectDoesNotExist: User has no auth_token.

### ISSUE THREAD

**Issue by agconti** [agconti/cookiecutter-django-rest#75]

**Comment by agconti** [comment]
@vpatel85 @glemmaPaul have you guys ran into this? 

I think this might not actually be a bug, but a problem with my local machine.

**Comment by glemmaPaul** [comment]
@agconti Haven't had that problem no!

**Comment by agconti** [comment]
@glemmaPaul thanks for letting me know!
