### ISSUE TITLE
Clean up merged branches on github

### ISSUE THREAD

**Issue by morenoh149** [agconti/cookiecutter-django-rest#761]
Just skimming the project. There are tons of merged branches on the github project. These could probably be removed with a oneliner.

**Comment by agconti** [comment]
@morenoh149 You're right, these branches could be removed. They aren't a problem either. This isn't a priority because there's no real value to doing it. I only have so much time that I can give to open source work. I try to make that time as impactful as I can.

**Comment by morenoh149** [comment]
as a potential contributor I found it difficult to find branches of interest like `master` or `gh-pages`. I find it difficult to see interesting work being done. The command is `git branch -r --merged | grep -v master | sed 's/origin\///' | xargs -n 1 git push --delete origin`
