### ISSUE TITLE
ModuleNotFoundError: No module named 'configurations'

### ISSUE THREAD

**Issue by stoyanovgeorge** [agconti/cookiecutter-django-rest#882]
#### What's going wrong?

I am trying to install the REST-API cookiecutter template on a Windows machine using conda. When I try to start the server I got the following error: `ModuleNotFoundError: No module named 'configurations'`. 

I also don't want to host this project on heroku or deploy a Docker image, I want to experiment with REST-API on my own self-hosted server. 

#### How can the `cookiecutter-django-rest` team reproduce the problem?

```
conda create -n venv python=3.7.0
conda activate venv
pip install django
pip install cookiecutter
cookiecutter gh:agconti/cookiecutter-django-rest
cd <cookiecutter-django-rest-dir>
python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    from configurations.management import execute_from_command_line
ModuleNotFoundError: No module named 'configurations'
```

#### Is this a problem with a fresh install of the project?

- [x] Yes
- [ ] No

**Comment by agconti** [comment]
Hey @stoyanovgeorge, you need to install the project's dependencies. Take a look at the ReadMe in your project's root directory for detailed instructions.
