### ISSUE TITLE
No such file or directory | exited with code 127

### ISSUE THREAD

**Issue by gianfrancolombardo** [agconti/cookiecutter-django-rest#884]
#### What's going wrong?

On `docker-compose up` show me:
`web_1            | /usr/bin/env: ‘python\r’: No such file or directory`

#### How can the `cookiecutter-django-rest` team reproduce the problem?

1. Run cookiecutter gh:agconti/cookiecutter-django-rest
2. Enter new folder project
3. Run docker-compose up
4. Console show me:
`web_1            | Postgres is ready! ✨ 💅`
`web_1            | /usr/bin/env: ‘python\r’: No such file or directory`
`testingrest_web_1 exited with code 127`

#### Is this a problem with a fresh install of the project?

- [x] Yes
- [ ] No

The steps are very simple and do not modify any file. 
Someone else happened to him?

`docker version`
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 

`docker info`
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 226
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d004201
ID: 4P5B:XERR:PCN6:JQZT:TFYU:QYEP:EHCV:FVRZ:JHRD:SV7X:YD3T:JF5X
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 47
 System Time: 2019-04-16T17:35:52.8424397Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

![docker-compose up output](https://user-images.githubusercontent.com/9468025/56231605-2aff5380-607f-11e9-918b-c99bc63c36e5.jpg)

**Comment by agconti** [comment]
Hi @gianfrancolombardo, it looks like you accidentally named your env with a carriage return, `‘python\r’`. You probably want `‘python‘`.  

Closing this now, but if you're still having issues please reopen!
