### ISSUE TITLE
Installing new packages requires pip install of all packages

### ISSUE THREAD

**Issue by noodlebreak** [agconti/cookiecutter-django-rest#900]
#### What's going wrong?

If I install a new Python package, then building the `web` container installs all the packages again. This is causing too much time delay when starting out the project and adding stuff as we build.

#### How can the `cookiecutter-django-rest` team reproduce the problem?

1. Setup the project as usual.
2. Add a new Python package to requirements.txt
3. Build `web` container.

You'll see that all the packages are installed fresh.

#### Is this a problem with a fresh install of the project?

- [ ] Yes
- [x] No

**Comment by agconti** [comment]
Thanks for opening up an issue @noodlebreak and thanks for the detailed answer @ScottBarkman! 💖 

@noodlebreak, the answer from Scott is also the answer I would give you.
