### ISSUE TITLE
Procfile is missing during project initialization.

### ISSUE THREAD

**Issue by stefanitsky** [agconti/cookiecutter-django-rest#901]
#### What's going wrong?

Procfile is missing during project initialization.

I am surprised that during the initialization of the project it was not created, although at the same time there is an instruction for deploying it to Heroku.

#### How can the `cookiecutter-django-rest` team reproduce the problem?

1. Create new project with cookiecutter
2. Try to deploy with heroku.

#### Is this a problem with a fresh install of the project?

- [x] Yes
- [ ] No

**Comment by stefanitsky** [comment]
Ok, i see #894, but as i understand it, it was removed from the README documentation, but was not removed from the documentation during project generation via [cookiecutter](https://github.com/agconti/cookiecutter-django-rest/blob/master/%7B%7Bcookiecutter.github_repository_name%7D%7D/docs/index.md#continuous-deployment), it misled me.

**Comment by agconti** [comment]
Ahh sorry about that @stefanitsky. Thank you for opening up a PR 💖

**Comment by stefanitsky** [comment]
> Ahh sorry about that @stefanitsky. Thank you for opening up a PR 💖

No, thank you for cookiecutter template 💅😊

**Comment by divadvo** [comment]
Hi! What is the process to deploy to Heroku now?
