### ISSUE TITLE
proposal Why don't you want to change docker to option?

### ISSUE THREAD

**Issue by cafju** [agconti/cookiecutter-django-rest#999]
#### What's going wrong?

Our team can't use docker because of bad security policies.

#### How can the `cookiecutter-django-rest` team reproduce the problem?

So, I suggest making the docker an option.

#### Is this a problem with a fresh install of the project?

- [x] Yes
- [ ] No

Thank you for your work. Stay healthy 👍 : )

**Comment by agconti** [comment]
Hi @binaryeast, you can choose to remove the Dockerfile and docker-compose file if you wish! It's there for your convenience, not as a requirement. 😄
